//! Transcript contract tests: what vx-rs actually produces for known audio.
//!
//! The unit tests in `src/main.rs` cover buffering and the hallucination filter, but
//! nothing pinned the *output* — a change to chunking, prompt, or sampling could
//! silently degrade every transcript and still ship green. These tests run the real
//! binary against the committed fixtures in `fixtures/audio/` and compare the result
//! to `fixtures/audio/goldens.json` (required keywords + a word-error-rate ceiling).
//!
//! Fixtures are macOS TTS clips regenerated by `Scripts/make-fixtures.sh`; re-key the
//! goldens afterwards with:
//!
//!   VX_UPDATE_GOLDENS=1 VX_REQUIRE_MODEL=1 cargo test --test transcript_contract
//!
//! Without a model these tests skip; `VX_REQUIRE_MODEL=1` turns that into a failure so
//! CI cannot pass vacuously. See `tests/common/mod.rs` for all env vars.

mod common;

use common::{assert_golden, fixture, model_guard, normalize, read_wav_f32, run_file, run_stream,
             stdout_text, wer};

/// The engine whose goldens these tests assert against.
///
/// To add a second engine (e.g. Parakeet): give each fixture a sibling key in
/// goldens.json (`"parakeet-v2": { … }`), then replace this constant with a loop over
/// the engine ids, resolving the binary and its arguments per engine in `common`.
/// The golden lookup, keyword check, and WER comparison are already engine-parameterized.
const ENGINE: &str = "whisper-tiny.en";

/// Transcribes a fixture through `stream` mode and asserts its golden.
fn assert_stream_fixture(name: &str) {
    require_model!(model);
    let _guard = model_guard();

    let samples = read_wav_f32(&fixture(name));
    let output = run_stream(&model, &samples);
    let transcript = stdout_text(&output);
    assert_golden(name, ENGINE, &transcript);
}

// ── stream mode: one test per fixture ────────────────────────────────────────

#[test]
fn stream_short_phrase() {
    assert_stream_fixture("short-phrase");
}

#[test]
fn stream_punctuation_numbers() {
    assert_stream_fixture("punctuation-numbers");
}

#[test]
fn stream_rule_trigger() {
    assert_stream_fixture("rule-trigger");
}

#[test]
fn stream_spoken_submit() {
    assert_stream_fixture("spoken-submit");
}

#[test]
fn stream_two_utterances() {
    assert_stream_fixture("two-utterances");
}

#[test]
fn stream_long_45s() {
    assert_stream_fixture("long-45s");
}

#[test]
fn stream_long_60s() {
    assert_stream_fixture("long-60s");
}

// ── file mode ────────────────────────────────────────────────────────────────

#[test]
fn file_short_phrase() {
    require_model!(model);
    let _guard = model_guard();

    let transcript = stdout_text(&run_file(&model, &fixture("short-phrase")));
    assert_golden("short-phrase", ENGINE, &transcript);
}

#[test]
fn file_long_45s() {
    require_model!(model);
    let _guard = model_guard();

    let transcript = stdout_text(&run_file(&model, &fixture("long-45s")));
    assert_golden("long-45s", ENGINE, &transcript);
}

// ── cross-mode and structural contracts ──────────────────────────────────────

/// `file` and `stream` share the same chunking and inference path, differing only in
/// how audio arrives. They must therefore agree closely; divergence means one path
/// mangled the samples (wrong scaling, dropped bytes, a stray resample).
#[test]
fn stream_and_file_agree_on_short_phrase() {
    require_model!(model);
    let _guard = model_guard();

    let wav = fixture("short-phrase");
    let from_file = stdout_text(&run_file(&model, &wav));
    let from_stream = stdout_text(&run_stream(&model, &read_wav_f32(&wav)));

    let rate = wer(&normalize(&from_file), &normalize(&from_stream));
    assert!(
        rate <= 0.1,
        "file and stream modes disagree (WER {rate:.3} > 0.100)\n\
         file:   {from_file:?}\n\
         stream: {from_stream:?}"
    );
}

/// Audio longer than the 30 s Whisper context is split into chunks and the parts are
/// rejoined. This asserts nothing falls out at the seam: the 45 s lighthouse story
/// spans two chunks, so words from *both* the opening (first ~10 s, chunk 1) and the
/// closing (last ~10 s, chunk 2) must survive. A dropped chunk still yields fluent
/// text and a plausible WER, so only end-to-end keyword coverage catches it.
#[test]
fn long_45s_crosses_chunk_boundary_without_loss() {
    require_model!(model);
    let _guard = model_guard();

    let transcript = stdout_text(&run_stream(&model, &read_wav_f32(&fixture("long-45s"))));
    let words = normalize(&transcript);
    let has = |w: &str| words.iter().any(|x| x == w);

    // Opening: "The lighthouse keeper climbed the spiral stairs every evening at dusk.
    //           He carried a brass lantern, a thermos of tea, and a worn logbook."
    let opening = ["lighthouse", "keeper", "spiral", "stairs", "dusk", "brass", "lantern"];
    // Closing: "After forty years he knew every stone of the tower… When the automatic
    //           lamp finally arrived, he stayed on for one more season, just to be sure."
    let closing = ["forty", "years", "tower", "automatic", "lamp", "season"];

    assert!(
        opening.iter().any(|w| has(w)),
        "transcript has no words from the first chunk of a 45 s recording — the opening \
         audio was dropped.\nlooked for {opening:?}\ntranscript: {transcript:?}"
    );
    assert!(
        closing.iter().any(|w| has(w)),
        "transcript has no words from the final chunk of a 45 s recording — audio past \
         the 30 s boundary was dropped.\nlooked for {closing:?}\ntranscript: {transcript:?}"
    );
}

/// The Swift side pastes stdout verbatim, so `stream` must emit at most one line
/// however many chunks it transcribed. long-60s spans three chunks; if the join ever
/// became a per-chunk `println!`, this catches it before a multi-line paste ships.
#[test]
fn stream_emits_at_most_one_line() {
    require_model!(model);
    let _guard = model_guard();

    let output = run_stream(&model, &read_wav_f32(&fixture("long-60s")));
    assert!(output.status.success(), "vx-rs stream exited with {:?}", output.status);

    let stdout = String::from_utf8_lossy(&output.stdout);
    let newlines = stdout.trim_end_matches('\n').matches('\n').count();
    assert_eq!(
        newlines, 0,
        "stream mode must emit at most one line, got {} lines:\n{stdout}",
        newlines + 1
    );
}
